### ISSUE TITLE
add ability to toggle player 4 off on 4p layouts

### ISSUE THREAD

**Issue by jsnkuhn** [Rando-Mania/RandoTracker#106]
At this point lots of folks use 4p layouts for 3 player races cuz there just are no 3p layouts in most cases.  Adding the ability to toggle player 4 off on 4p layouts would be a good start.

toggle should remover player fours name and tracking icons at the very least maybe also the video window

defaulting to having the randomizer's logo in the background of at least player 4s video window also seems to help for those not using color/chroma filtering

**Comment by jsnkuhn** [comment]
Should be as simple as toggling this:

```css
[player="4"], .player-info-contain:nth-of-type(4){
  display: none;
}
```
above code is specific to FF6WC might be a bad example but general idea is still there.

Can be done on all layouts globally through a toggle in the menu

**Comment by jsnkuhn** [comment]
for those layouts with 4 timers...

```css
.hide-p4 [player="4"],
.hide-p4 tr-timer:nth-of-type(4), 
.hide-p4 .player-info-contain:nth-of-type(4){
    display: none;
}
```

clipping mask will need adjusting to just clip 3 videos
