### ISSUE TITLE
allow easy text/icon color change

### ISSUE THREAD

**Issue by jsnkuhn** [Rando-Mania/RandoTracker#174]
Black or white icon coloring is all that has been requested to this point so it's all i've bothered prepping for. Points to @Soleras3 for figuring out how to change the production icon coloring with css `filter` but it shouldn't be this hard.

```css
.sidebar-staff-players .staff img{
    /* pre-filter comms/stream/tracker icons to black, then convert to #dfd2b4
       see: https://codepen.io/sosuke/pen/Pjoqqp */
    filter: brightness(0) saturate(100%) invert(81%) sepia(21%) saturate(280%) hue-rotate(4deg) brightness(104%) contrast(85%)
}
```

If we changed to using inline svg for the icons we can just use `fill="currentColor"` to automatically change the icon fill color based on the CSS `color` property. This should also allow the icons to easily be a different color than the text if wanted.

```css
.layout{
  color: #b1ffed;
}
.staff svg path{
  color: #facade;
}
```
