### ISSUE TITLE
replace tr-hide-if-empty with `:has` 

### ISSUE THREAD

**Issue by jsnkuhn** [Rando-Mania/RandoTracker#215]
We currently have a `tr-hide-if-empty` component to hide a parent element if one of it's child/grandchild etc elements is empty. Once `:has` is supported in the OBS inbuilt version of chromium we can likely do away with `tr-hide-if-empty` altogether.

```css
.container:has(.results:empty) {
  display: none;
}
```

https://tobiasahlin.com/blog/hiding-an-element-if-its-empty/
