### ISSUE TITLE
`object-view-box` for tracking icons

### ISSUE THREAD

**Issue by jsnkuhn** [Rando-Mania/RandoTracker#221]
Look into using CSS `object-view-box` for tracking Icons in replace of CSS background images on transparent SVGs in img tag. 

This CSS property is in only chrome (104+) for now. OBS currently uses chrome 103 needs at least one more update (if not 2) before we can use reliably: 

https://caniuse.com/?search=object%20view%20box

Codepen with experimenting:

https://codepen.io/jsnkuhn/pen/oNdKymy 

```css
img{
  object-view-box: xywh(40% 40% 32px 32px);
}
```

instead of this:

```css
.sprite {
    background-image: url(images/item/item-sprite.png);
    background-repeat: no-repeat;
}

.sprite-bridge-transparent {
    background-position: 0 0;
}
```
